spring.application.name=springboot
# 1. データベースの名前を固定する（ランダムになるのを防ぐ）
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# 2. 【ここが原因！】データベースの動き（SQL）をコンソールに表示する
spring.jpa.show-sql=true

# 3. ブラウザからデータベースの中身を覗き見できるようにする設定
spring.h2.console.enabled=true